[package]
name = "modgasm"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_derive = "1"
serde = "1"
json5 = "0.4"
serde_json = "1"
text_io = "0.1"
inquire = "0.7"
futures = "0.3"
